--사용자 테이블 생성
CREATE TABLE USERS( 
  ID VARCHAR(20) NOT NULL PRIMARY KEY,
  UNAME VARCHAR(20) NOT NULL,
  POINT INT DEFAULT 0,
  PHONE VARCHAR(20)
);

DESC USERS; --테이블 구조 확인 하는 명령어

--메세지 테이블 생성
CREATE TABLE MESSAGES(
  MID INT NOT NULL PRIMARY KEY,
  SENDER VARCHAR(20) NOT NULL,
  RECEIVER VARCHAR(20) NOT NULL,
  SDATE DATE DEFAULT SYSDATE,
  MESSAGE VARCHAR(1000) NOT NULL,
  FOREIGN KEY (SENDER) REFERENCES USERS (ID),
  FOREIGN KEY (RECEIVER) REFERENCES USERS (ID)
);

--사용자 입력
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('blue','이블루', 20, '010-1010-1010');
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('red','박레드', 10, '010-1010-2020');
INSERT INTO USERS(ID, UNAME, POINT, PHONE)
VALUES('green','최그린', 10, '010-1010-3030');

DELETE FROM USERS;
SELECT * FROM USERS;

--메세지 번호 시퀀스 생성
CREATE SEQUENCE SEQ_MID START WITH 1 INCREMENT BY 1;

--메세지 입력
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES (SEQ_MID.NEXTVAL, 'blue', 'red', SYSDATE, '레드야 잘지내지?');
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES (SEQ_MID.NEXTVAL, 'red', 'blue', SYSDATE, '블루야 오랜만이야');
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES (SEQ_MID.NEXTVAL, 'green', 'blue', SYSDATE, '폭우 조심해');
INSERT INTO MESSAGES(MID, SENDER, RECEIVER, SDATE, MESSAGE)
VALUES (SEQ_MID.NEXTVAL, 'blue', 'green', SYSDATE, '고마워 조심할게');

DELETE FROM MESSAGES;
SELECT * FROM MESSAGES;

--블루가 보낸 메세지만 출력
SELECT M.*, U.UNAME, PHONE
FROM MESSAGES M, USERS U 
WHERE SENDER='blue' AND U.ID=M.RECEIVER;

--블루가 받은 메세지
SELECT M.*, UNAME, PHONE
FROM MESSAGES M, USERS U
WHERE RECEIVER='blue' AND SENDER=ID;

COMMIT;

ALTER TABLE MESSAGES ADD SDEL INT DEFAULT 0;
ALTER TABLE MESSAGES ADD RDEL INT DEFAULT 0;

SELECT * FROM MESSAGES;